name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    name: "Build docker and publish to ECR"
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
  
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
  
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 756014088805.dkr.ecr.sa-east-1.amazonaws.com
        ECR_REPOSITORY: /mlgroup/embrapa
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      
#    runs-on: ubuntu-latest
#    steps:
#      - name: Login to ECR
#        uses: docker/login-action@v3
#        with:
#          registry: 756014088805.dkr.ecr.sa-east-1.amazonaws.com
#          username: ${{ vars.ECR_USERNAME }}
#          password: ${{ secrets.ECR_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          context: .
#          tags: 756014088805.dkr.ecr.sa-east-1.amazonaws.com/mlgroup/embrapa:latest
#          file: ./Dockerfile
