name: CI/CD Workflow

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 756014088805.dkr.ecr.sa-east-1.amazonaws.com
          username: ${{ vars.ECR_USERNAME }}
          password: ${{ secrets.ECR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: 756014088805.dkr.ecr.sa-east-1.amazonaws.com/mlgroup/embrapa:latest
          file: ./Dockerfile
